name: playx
description: playx project
version: 0.0.4
homepage: https://sourcya.com/

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_readable: ^0.0.5
  get: ^4.6.5
  playx_core: ^0.0.2
  playx_theme: ^0.0.1+1
  queen_validators: ^1.0.0
  sentry_flutter: ^6.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
