name: playx
description: playx project
version: 0.0.6
homepage: https://sourcya.com/

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_readable: ^0.0.6
  get: ^4.6.5
  playx_core: ^0.0.2
  playx_theme: ^0.0.1+1
  queen_validators: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
